
theme = "kanagawa-transparent"
# transparent = true

[editor]
auto-format = true
line-number = "relative"
scrolloff = 4
auto-completion = true
auto-save = true
completion-timeout = 50
completion-replace = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
